### ISSUE TITLE
Verwachte waarden 'Vandaag' worden niet bijgewerkt.

### ISSUE THREAD

**Issue by poiterb** [bochove/nl.bochove.knmi#23]
Alle verwachte waarden voor vandaag worden niet meer bijgewerkt, zijn voor het laatst 10 dagen of nog ouder bijgewerkt.
Alle andere waarden worden nog wel bijgewerkt, het gaat dus alleen om de 'Vandaag' waarden.
Versie is  0.1.15.

**Comment by Rvvliet1970** [comment]
Ik ervaar helaas het zelfde

**Comment by Francois1974** [comment]
Helaas hier ook zo. Graag oplossen

**Comment by vicdelfant** [comment]
Als aanvulling: de API van weerlive.nl geeft (met dezelfde API key die is geconfigureerd in de Homey app) wel de juiste waarden. De temperatuur lijkt wel in het Homey device te worden bijgewerkt, maar bijvoorbeeld de verwachte neerslag niet.

Het herstarten van de Homey app maakt overigens ook geen verschil.

**Comment by vicdelfant** [comment]
Na wat verder te hebben gezocht: er lijkt verschil te zitten in de resultaten van de endpoints van weerlive.nl. Deze Homey app gebruikt…

https://github.com/bochove/nl.bochove.knmi/blob/6ba7d643bb7bbc5562ee19771876a43391d44046/drivers/knmi/driver.js#L32

… waar bijvoorbeeld voor vandaag en mijn locatie `33` als neerslagkans wordt gerapporteerd, wat overeenkomt met de foutieve waarden die in Homey worden weergegeven.

In dit zin ligt de fout dus niet bij deze applicatie, maar de API. Via het v2 endpoint van weerlive.nl (bijv. https://weerlive.nl/api/weerlive_api_v2.php?key=demo&locatie=Amsterdam) komt de juiste data binnen, maar logischerwijs in een formaat waar de app nog niet mee kan omgaan.

**Comment by poiterb** [comment]
Ok, dan ligt het probleem dus niet bij de app, maar bij de Weerlive api. Ik heb Weerlive een mail gestuurd, kijken of ze gaan reageren...

**Comment by poiterb** [comment]
hmm, helaas, mail naar post@weerlive.nl is gebounced (TLS issue)en via de contact pagina doet de captcha het niet...

**Comment by poiterb** [comment]
Hij doet het weer! (ook nog mail gestuurd naar meteoserver, en dat heeft blijkbaar geholpen)
