### ISSUE TITLE
missing_droptoken

### ISSUE THREAD

**Issue by Mdev21** [bochove/nl.bochove.knmi#7]
Hi, how are you doing? I seem to have problems with the KNMI app / device. Installing the app on my homey seems to be succesfull as I checked the status using the homey developers interfaces / device section. All weather info is correctly available.

Using a simple flow like Als 'Nieuwe gegevens van het KNMI', en 'Plaats' (logic) bevat Arnhem dan "willekeurige actie" levert als ik een test uitvoer op de logica (de En stap) een foutmelding op: missing_droptoken. Enig idee wat er mis gaat?

Gr,
Michael

**Comment by bochove** [comment]
Wanneer je het device geïnstaleerd hebt is het niet nodig om de kaart 'Nieuwe gegevens van het KNMI' te gebruiken.
Je kunt direct de waarden van het KNMI gebruiken.
Dus als tijd = ... en 'logic kaart met KNMI verwachte max temperatuur vandaag' groter dan ... dan willekeurige actie.


Wanneer je er niet de behoefte toe hebt om iedere 10 minuten bij het KNMI aan te kloppen dan kun je er ook voor kiezen om eenmalig even te kijken wat de huidige waarden zijn, door de 'dan' kaart 'Haal nieuwe gegevens op' af te vuren.
Nadat die laatste afgevuurd wordt kun je de als 'Nieuwe gegevens van het KNMI' ontvangen kaart gebruiken met de waarden die daaraan meegegeven worden. Maar wanneer je reeds het device geïnstaleerd hebt, is dat niet meer nodig omdat je dan altijd al de laatste gegevens zult hebben.
