### ISSUE TITLE
Max frequenty changed

### ISSUE THREAD

**Issue by DimitryNL** [bochove/nl.bochove.knmi#8]
According to http://www.weerlive.nl/real-time-KNMI-weer-API.php the max frequenty has changed to max 500 API calls a month. Is it possible to have it updated & cached once every 1,5 hour, which should get you through one month.

**Comment by bochove** [comment]
That is Meteoserver, the api that I make use of is:
https://weerlive.nl/delen.php
> API Key
> Toegang tot de API loopt via een API key, [deze kun je hier opvragen](https://weerlive.nl/api/toegang/index.php). De key is gratis en de API is gratis (en as is). Houd wel de datalimiet in de gaten: je kunt maximaal 300 dataverzoeken per dag doen.

So as I see it, nothing is changed.
Additionally, it currently is the 23rd of the month and I am personally still receiving normal responses from the api, that is, containing the requested data. With requests fired every 10 minutes that means that I've fired nearly 3500 requests at the api for this month, well over the 500 threshold you mentioned and all is still functioning as it should be.
