### ISSUE TITLE
Ik kom niet verder

### ISSUE THREAD

**Issue by FonsdeRond** [bochove/nl.bochove.knmi#9]
Ik werk met de Homey. Ik heb een eenvoudige flow gemaakt die de gegevens ophaalt (die flow geeft geen fouten als ik test )en een flow die wordt getrikkerd als er nieuwe gegeven zijn en me een pushbericht stuurt. Dat pushbericht komt binnen.
Kortom ik dacht daarmee de variabelen zouden zijn gevuld. Echter als ik dat een 'als'-kaart wil maken, dan is alleen de kaart 'Nieuwe gegevens van het KNMI' te zien.

Wat doe ik fout.

**Comment by bochove** [comment]
In de als gebruik je logica kaarten, dus geen kaarten van KNMI. In de logica kaarten kun je dan de waarden (tags) van het KNMI gebruiken.

**Comment by FonsdeRond** [comment]
Het was een ander probleem. Het is blijkbaar noodzakelijk om eerst een nieuw 'apparaat' te installeren. Het 'KNMI-apparaat'. Dat heb ik blijkbaar ergens gemist. Maar nu werkt het.
